build:
  image: centos:7
  commands:
#    - yum install -y epel-release
#    - yum install -y nodejs npm
#    - npm -d install
#    - npm install -g mocha
#    - mocha
#
deploy:
  ssh:
    host: 192.168.99.1
    port: 2022
    user: walsh
    commands:
      - echo "hello" > /tmp/hello.txt
