#!/bin/bash

function start() {
  if [ -f ./server.pid ]; then
    if ! kill -0 `cat server.pid` > /dev/null 2>&1; then
      rm -f ./server.pid
    else
      echo "node server already running."
      exit -1
    fi
  fi

  echo "Starting node server."
  /usr/local/bin/node server &
  echo $! > ./server.pid
  echo -n "PID is "
  echo -n `cat server.pid`
  echo
}

function stop() {
  if [ -f ./server.pid ]; then
    echo -n "Stopping node server for PID of "
    echo `cat server.pid`
    kill -9 `cat server.pid`
    rm -f ./server.pid
    echo
  fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
